# Deploy OD to the remote server and push secrets

name: deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Transfer latest to remote
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWD }}
          port: ${{ secrets.REMOTE_PORT }}
          source: "otherdave/*, data/*, images/*, conf.yaml, requirements.txt, setup.py"
          target: "~/OtherDave"
      - name: Push secrets and restart service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWD }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            printf ${{ secrets.DISCORD_TOKEN }} > bot.tkn
            printf ${{ secrets.POLYGON_TOKEN }} > poly.tkn
            sudo systemctl restart otherdave
